### ISSUE TITLE
Høsting av Nasjonalbibliotekets katalog feiler

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-dataset-harvester#102]
Se siste kommentar

`"org.apache.jena.riot.RiotException: [line: 76, col: 34] Unrecognized (expected an RDF Term): [SEMICOLON]
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:163)
	at org.apache.jena.riot.lang.LangEngine.raiseException(LangEngine.java:148)
	at org.apache.jena.riot.lang.LangEngine.exceptionDirect(LangEngine.java:143)
	at org.apache.jena.riot.lang.LangEngine.exception(LangEngine.java:137)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesNodeCompound(LangTurtleBase.java:489)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesNode(LangTurtleBase.java:469)
	at org.apache.jena.riot.lang.LangTurtleBase.objectList(LangTurtleBase.java:419)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:352)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:345)
	at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:314)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:178)
	at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
	at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:79)
	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:43)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:197)
	at org.apache.jena.riot.RDFParser.read(RDFParser.java:370)
	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:356)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:306)
	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:552)
	at org.apache.jena.riot.RDFDataMgr.parseFromReader(RDFDataMgr.java:728)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:287)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:271)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:62)
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:246)
	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.rdf.RDFUtilsKt.parseRDFResponse(RDFUtils.kt:48)
	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.harvester.DatasetHarvester.harvestDatasetCatalog(DatasetHarvester.kt:36)
	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.harvester.HarvesterActivity$initiateHarvest$harvest$1$1$3$1.invokeSuspend(HarvesterActivity.kt:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Parse from https://www.nb.no/sprakbanken/oai/dct_ttl has failed"`

**Comment by NilsOveTen** [comment]
@stigbd 
Etter som jeg ser så er det pga manglende verdi for keyword på linje 76: `dcat:keyword             ;`

Testet raskt der jeg la inn en verdi, da ble høstingen gjennomført, tar du kontakt med de ang. dette?

**Comment by valosnah** [comment]
@stigbd Veldig lik [den du nettopp lukket](https://github.com/Informasjonsforvaltning/fdk-dataset-harvester/issues/114), men her er kilden ekstern

**Comment by valosnah** [comment]
Ser nå at denne har endret seg. 
org.apache.jena.riot.RiotException: [line: 292, col: 1 ] Broken token (newline): Commercial Use of DanNet

> org.apache.jena.riot.RiotException: [line: 292, col: 1 ] Broken token (newline): Commercial Use of DanNet
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:163)
	at org.apache.jena.riot.tokens.TokenizerText.fatal(TokenizerText.java:1342)
	at org.apache.jena.riot.tokens.TokenizerText.readString(TokenizerText.java:777)
	at org.apache.jena.riot.tokens.TokenizerText.parseToken(TokenizerText.java:239)
	at org.apache.jena.riot.tokens.TokenizerText.hasNext(TokenizerText.java:90)
	at org.apache.jena.atlas.iterator.PeekIterator.fill(PeekIterator.java:50)
	at org.apache.jena.atlas.iterator.PeekIterator.next(PeekIterator.java:92)
	at org.apache.jena.riot.lang.LangEngine.nextToken(LangEngine.java:98)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:351)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:345)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesBlankNode(LangTurtleBase.java:502)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesBlankNode(LangTurtleBase.java:496)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesNodeCompound(LangTurtleBase.java:484)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesNode(LangTurtleBase.java:469)
	at org.apache.jena.riot.lang.LangTurtleBase.objectList(LangTurtleBase.java:419)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:352)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:345)
	at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:314)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:178)
	at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
	at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:79)
	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:43)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:197)
	at org.apache.jena.riot.RDFParser.read(RDFParser.java:370)
	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:356)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:306)
	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:552)
	at org.apache.jena.riot.RDFDataMgr.parseFromReader(RDFDataMgr.java:728)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:287)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:271)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:62)
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:246)
	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.rdf.RDFUtilsKt.parseRDFResponse(RDFUtils.kt:46)
	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.harvester.DatasetHarvester.harvestDatasetCatalog(DatasetHarvester.kt:68)
	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.harvester.HarvesterActivity$initiateHarvest$1$1$3$1.invokeSuspend(HarvesterActivity.kt:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Harvest of https://www.nb.no/sprakbanken/oai/dct_ttl failed

**Comment by stigbd** [comment]
Det er ei rekke syntaktiske feil i denne fila:
- multiline string må omringast av triple quotes: """ multiline string """,
- quotes i tekst må escapes: ""asdf" asdf" -> "\"asdf\" asdf"
- property utan object må fjernes

**Comment by stigbd** [comment]
Melding frå utgivar:
> Vi har gjort noen endringer, først og fremst brukt """tredoble anførselstegn""" rundt flere av verdiene. Validering og innhøsting ser ut for å fungere nå.
