### ISSUE TITLE
Bad character in IRI: https://hotell.difi.no/?dataset=brreg/sektorkode[space]...

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-dataset-harvester#114]
Høsteren feiler under høsting av Brregs katalog: https://dataset-catalog.fellesdatakatalog.digdir.no/catalogs/974760673
Ser ut som et av datasettene har en ugyldig lenke?

org.apache.jena.riot.RiotException: [line: 2009, col: 104] Bad character in IRI (space): <https://hotell.difi.no/?dataset=brreg/sektorkode[space]...>
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:156)
	at org.apache.jena.riot.tokens.TokenizerText.error(TokenizerText.java:1334)
	at org.apache.jena.riot.tokens.TokenizerText.readIRI(TokenizerText.java:532)
	at org.apache.jena.riot.tokens.TokenizerText.parseToken(TokenizerText.java:194)
	at org.apache.jena.riot.tokens.TokenizerText.hasNext(TokenizerText.java:90)
	at org.apache.jena.atlas.iterator.PeekIterator.fill(PeekIterator.java:50)
	at org.apache.jena.atlas.iterator.PeekIterator.next(PeekIterator.java:92)
	at org.apache.jena.riot.lang.LangEngine.nextToken(LangEngine.java:98)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:351)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:345)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesBlankNode(LangTurtleBase.java:502)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesBlankNode(LangTurtleBase.java:496)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesNodeCompound(LangTurtleBase.java:484)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesNode(LangTurtleBase.java:469)
	at org.apache.jena.riot.lang.LangTurtleBase.objectList(LangTurtleBase.java:419)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:352)
	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:345)
	at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:314)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:178)
	at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
	at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:79)
	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:43)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:197)
	at org.apache.jena.riot.RDFParser.read(RDFParser.java:370)
	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:356)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:306)
	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:552)
	at org.apache.jena.riot.RDFDataMgr.parseFromReader(RDFDataMgr.java:728)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:287)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:271)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:62)
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:246)
	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.rdf.RDFUtilsKt.parseRDFResponse(RDFUtils.kt:46)
	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.harvester.DatasetHarvester.harvestDatasetCatalog(DatasetHarvester.kt:68)
	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.harvester.HarvesterActivity$initiateHarvest$1$1$3$1.invokeSuspend(HarvesterActivity.kt:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by stigbd** [comment]
Det enklaste er å gå inn å fjerne trailing space i datasett-registrering.

**Comment by stigbd** [comment]
@KurtStian Har du tilgang til å endre på et datasett som Brønnøysundregistrene eig? Det gjelder Enhetsregisteret og distribusjon som har tittel "Sektorkoder i Enhetsregisteret":
- Fjerne trailing space i feltet accessURL

**Comment by stigbd** [comment]
Forøvrig er det litt rart at registreringsløysing kan lage rdf som ikkje er syntaktisk korrekt.
