### ISSUE TITLE
Spring ser ut til å blokkere harvest,completed-meldingen

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-dataset-harvester#126]
Dette fører til at flyten videre igjennom reasoning-service og fulltext-search ikke virker.
Endringer i høstet data ender ikke opp i portalen.

> fdk-dataset-harvester
> org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "//"
> 	at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlocklistedUrls(StrictHttpFirewall.java:535)
> 	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:505)
> 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:206)
> 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
> 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
> 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
> 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

**Comment by valosnah** [comment]
Fixed by https://github.com/Informasjonsforvaltning/fdk-dataset-harvester/pull/127
