### ISSUE TITLE
Tjeneste gir 500 ved Bad character in IRI (space)

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-dataset-harvester#38]
Ref stacktrace:
```
stack_trace: "o.a.j.r.RiotException: [line: 4797, col: 121] Bad character in IRI (space): <http://data.brreg.no/enhetsregisteret/enhet/844[space]...>
	at o.a.j.r.s.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:147)
	at o.a.j.r.l.LangEngine.raiseException(LangEngine.java:148)
	at o.a.j.r.l.LangEngine.nextToken(LangEngine.java:105)
	at o.a.j.r.l.LangNQuads.parseOne(LangNQuads.java:67)
	at o.a.j.r.l.LangNQuads.runParser(LangNQuads.java:54)
	at o.a.j.r.l.LangBase.parse(LangBase.java:41)
	at o.a.j.r.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:191)
	at o.a.j.riot.RDFParser.read(RDFParser.java:352)
	at o.a.j.riot.RDFParser.parseNotUri(RDFParser.java:342)
	at o.a.j.riot.RDFParser.parse(RDFParser.java:291)
	at o.a.j.r.RDFParserBuilder.parse(RDFParserBuilder.java:540)
	at o.a.j.r.RDFDataMgr.parseFromInputStream(RDFDataMgr.java:901)
	at o.a.j.r.RDFDataMgr.read(RDFDataMgr.java:590)
	at o.a.j.r.RDFDataMgr.read(RDFDataMgr.java:568)
	at o.a.j.r.RDFDataMgr.read(RDFDataMgr.java:559)
	at o.a.j.r.RDFConnectionRemote.lambda$fetchDataset$12(RDFConnectionRemote.java:485)
	at o.a.jena.system.Txn.exec(Txn.java:77)
	at o.a.jena.system.Txn.executeWrite(Txn.java:125)
	at o.a.j.r.RDFConnectionRemote.fetchDataset(RDFConnectionRemote.java:480)
	at n.d.i.f.f.DatasetFuseki.fetchCompleteModel(DatasetFuseki.kt:23)
	at n.d.i.f.s.DatasetService.getAllDatasets(DatasetService.kt:14)
	at n.d.i.f.c.DatasetsController.getDatasets(DatasetsController.kt:35)
	at n.d.i.f.c.DatasetsController$$FastClassBySpringCGLIB$$fca56cdf.invoke(<generated>)
	at o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)
	at o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at o.s.v.b.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:120)
	at o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at o.s.a.f.CglibAop...
```
Vi må undersøke muligheita for å 
1. Logge betre kva for objekt som har feil,
2. Vurdere å "droppe" objektet med feil og returnere "sunne" objekter.

**Comment by stigbd** [comment]
Og vi må vurdere om vi kan validere data før vi lagrer. Vi burde ikkje putte data inn som vi ikkje får ut etterpå.

**Comment by lillelars** [comment]
Klarer ikke gjenskape. Lukker feilen inntil det eventuelt dukker opp igjen.
