### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-dataset-harvester#8]
Frå https://console.cloud.google.com/errors/CIfPuauXr6GEtwE?time=P1D&project=fdk-prod&authuser=2&organizationId=382284307604
```
java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133)
	at no.dcat.harvester.crawler.handlers.ElasticSearchResultHandler.lambda$filterValidationMessagesForDataset$8(ElasticSearchResultHandler.java:923)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at no.dcat.harvester.crawler.handlers.ElasticSearchResultHandler.filterValidationMessagesForDataset(ElasticSearchResultHandler.java:924)
	at no.dcat.harvester.crawler.handlers.ElasticSearchResultHandler.createDatasetHarvestRecord(ElasticSearchResultHandler.java:783)
	at no.dcat.harvester.crawler.handlers.ElasticSearchResultHandler.saveDatasetAndHarvestRecord(ElasticSearchResultHandler.java:730)
	at no.dcat.harvester.crawler.handlers.ElasticSearchResultHandler.updateDatasets(ElasticSearchResultHandler.java:366)
	at no.dcat.harvester.crawler.handlers.ElasticSearchResultHandler.indexWithElasticsearch(ElasticSearchResultHandler.java:201)
	at no.dcat.harvester.crawler.handlers.ElasticSearchResultHandler.process(ElasticSearchResultHandler.java:143)
	at no.dcat.harvester.crawler.CrawlerJob.run(CrawlerJob.java:171)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lillelars** [comment]
ser ut til å være knyttet til en feil i den gamle datasetthøsteren
og ikke minst i brreg-GCP'en. Lukker saken
